fullnameOverride: nami-services
replicaCount: 2
image:
  repository: 560978416398.dkr.ecr.us-east-1.amazonaws.com/nami-services
  tag: v1.0.0 ## ARM64

imagePullSecrets:
  - name: regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 8080